version: '3'

services:

  gui:
    build:
      context: ./GUI
      dockerfile: Dockerfile
    ports:
      - "8262:8200"

  web_scipy:
    build:
      context: ./web_SciPy
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8260:5000"
    depends_on:
      - redis_scipy
    volumes:
      - ./SciPy:/web_SciPy/SciPy

  worker_scipy:
    build:
      context: ./worker_SciPy
      dockerfile: Dockerfile
    depends_on:
      - redis_scipy
    volumes:
      - ./SciPy:/worker_SciPy/SciPy

  web_r:
    build:
      context: ./web_R
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8261:5000"
    depends_on:
      - redis_r
    volumes:
      - ./R:/web_R/R

  worker_r:
    build:
      context: ./worker_R
      dockerfile: Dockerfile
    depends_on:
      - redis_r
    volumes:
      - ./R:/worker_R/R

  web_scilab:
    build:
      context: ./web_Scilab
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8263:5000"
    depends_on:
      - redis_scilab
    volumes:
      - ./Scilab:/web_Scilab/Scilab

  worker_scilab:
    build:
      context: ./worker_Scilab
      dockerfile: Dockerfile
    depends_on:
      - redis_scilab
    volumes:
      - ./Scilab:/worker_Scilab/Scilab

  redis_scipy:
    image: redis
    ports:
     - "6379:6379"

  redis_r:
    image: redis
    ports:
     - "6380:6379"

  redis_scilab:
    image: redis
    ports:
     - "6383:6379"
